# Generated by Django 3.1.3 on 2020-11-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Watch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('image_url', models.ImageField(upload_to='')),
                ('description', models.TextField()),
                ('specifications', models.CharField(max_length=250)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
