# Generated by Django 3.1.3 on 2020-11-29 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watch',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='watch',
            name='image_url',
        ),
        migrations.AddField(
            model_name='watch',
            name='image',
            field=models.ImageField(default=1, upload_to='watches'),
            preserve_default=False,
        ),
    ]
