# Generated by Django 3.1.3 on 2020-11-29 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_watch_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watch',
            name='specifications',
        ),
    ]
