# Generated by Django 3.1.3 on 2020-12-02 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20201201_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watch',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
