# Generated by Django 3.1.3 on 2020-12-10 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_auth', '0002_auto_20201201_1328'),
        ('store', '0006_auto_20201202_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store_auth.userprofile')),
                ('watch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.watch')),
            ],
        ),
    ]
