# Generated by Django 3.1.3 on 2020-12-12 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='pet',
            new_name='watch',
        ),
    ]
