# Generated by Django 3.1.3 on 2020-12-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20201212_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='slug',
            field=models.SlugField(default=1, editable=False),
            preserve_default=False,
        ),
    ]
