# Generated by Django 3.1.3 on 2020-12-13 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_watch_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watch',
            name='slug',
        ),
    ]
