# Generated by Django 3.1.3 on 2020-12-13 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_auth', '0003_auto_20201213_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='date_of_birth',
            field=models.DateTimeField(),
        ),
    ]
